## GENERAL CONFIG ##
ansible_python_interpreter: /usr/bin/python3
ansible_connection: ssh
ansible_ssh_user: ubuntu
ansible_ssh_private_key_file: ~/.ssh/ansible
ansible_become: true
ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
user_home: /home/{{ ansible_ssh_user }}

## DATABASE ##
db_add_user_username: db-user01
db_add_user_password: password
db_add_user_db: db01
db_data_dir: /var/lib/mysql