---
- name: Install mysql-server
  apt:
    name: mysql-server
    update_cache: yes
  when: ('database' in group_names)

- name: Install python3-mysqldb
  apt:
    name: python3-mysqldb
    state: present
  when: ('database' in group_names)

- name: Configure mysql
  template:
    src: mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  notify: Restart mysql

- name: Start mysql service
  service:
    name: mysql
    state: started
    enabled: yes
  when: ('database' in group_names)

- name: Create new database
  mysql_db:
    name: "{{ db_add_user_db }}"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
  when: ('database' in group_names)

- name: Create database user
  mysql_user:
    name: "{{ db_add_user_username }}"
    password: "{{ db_add_user_password }}"
    priv: "{{ db_add_user_db }}.*:ALL"
    state: present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  when: ('database' in group_names)
